### ISSUE TITLE
Avoid memory leak

### ISSUE THREAD

**Issue by alekseykulikov** [ChiperSoft/morgan-debug#2]
Hey,
it seems that current implementation produces memory leak: https://github.com/ChiperSoft/morgan-debug/blob/master/morgan-debug.js#L10
this stream never ends and slowly grows with log strings.

**Comment by Twipped** [comment]
Oh... yeah, I guess if nothing ever listens to the stream it would just keep piling up. That's a pretty big leak.

Thanks, I'll try to fix this.

**Comment by Twipped** [comment]
This has now been fixed with 9b246e354e0a845ae188355e8b1df0b1563070eb in v1.1.0

I've also published v2.0.0 which makes morgan and debug peer dependencies.

**Comment by alekseykulikov** [comment]
thank you for such a quick fix!
